services:
  etherwake-website:
    container_name: etherwake-website
    image: ghcr.io/theking349/etherwake-website
    restart: always
    ports:
      - "8089:80"
    volumes:
      - ./devices.json:/usr/src/app/views/data/devices.json
      - ./.env:/usr/src/app/.env
networks:
  default:
    external: true
    name: redis_network