services:
  etherwake-website:
    container_name: etherwake-website
    image: ghcr.io/theking349/etherwake-website
    restart: always
    ports:
      - "8089:80"
    environment:
      - REDIS_HOST=[REDIS_HOST_HERE]
      - SSH_HOST=[SSH_HOST_HERE]
      - SSH_USER=[SSH_USERNAME_HERE]
      - SSH_PASSWORD=[SSH_PASSWORD_HERE]
      - SESSION_SECRET=[SECRET_HERE]
    volumes:
      - ./devices.json:/usr/src/app/views/data/devices.json
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data: